### ISSUE TITLE
A problem and a solution with strange file names including # and @

### ISSUE THREAD

**Issue by DavidSpivey** [will-moss/erin#28]
I like to keep my TikTok downloads with filenames resembling the original feed. This doesn't work in erin.

File names like

`Deets - Replying to @Ruthie🤍 bowl plate ＞＞＞＞ #bowlplate .mp4`

are improperly encoded because of encodeURI, which does not encode # and @ symbols.
This means the media file cannot be served, because caddy thinks # is part of the URL that needs to be stripped away.

The result is the browser console saying

`HTTP “Content-Type” of “text/html” is not supported. Load of media resource http://[myserver]/media/Deets%20-%20Replying%20to%20@Ruthie%F0%9F%A4%8D%20bowl%20plate%20%EF%BC%9E%EF%BC%9E%EF%BC%9E%EF%BC%9E%20#bowlplate%20.mp4?hash= failed.`

The lack of encoding @ and # are the problem, because requesting the urlencoded version works.

`http://[myserver]/media/Deets%20-%20Replying%20to%20%40Ruthie%F0%9F%A4%8D%20bowl%20plate%20%EF%
BC%9E%EF%BC%9E%EF%BC%9E%EF%BC%9E%20%23bowlplate%20.mp4`

So the solution is to properly encode the file name. By editing components/VideoCard/index.jsx we can make it work.

```
// Dependencies
import { useCallback, useRef } from "react";

// Assets
import "./index.css";

const VideoCard = ({ index, url, isLoaded, refForwarder, onDoubleClick }) => {
  const videoRef = useRef(null);

  // Handle click
  // - Seek forward / backward on double click
  const handleDoubleClick = (e) => {
    onDoubleClick(e);
  };

  const forward = useCallback((_ref) => {
    videoRef.current = _ref;
    refForwarder(_ref);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // Safely encode only the filename part of the URL
  let safeUrl = null;
  if (isLoaded && url) {
    try {
      const u = new URL(url); // parse full URL
      const parts = u.pathname.split("/");
      const last = parts.pop(); // filename
      parts.push(encodeURIComponent(last)); // encode filename only
      u.pathname = parts.join("/");
      safeUrl = u.toString();
    } catch (e) {
      console.error("Invalid URL in VideoCard:", url, e);
      safeUrl = url; // fallback to original
    }
  }

  return (
    <div className="video">
      <video
        className="player"
        data-index={index}
        src={safeUrl}
        ref={forward}
        onDoubleClick={handleDoubleClick}
        playsInline={true}
        muted={true}
        preload="auto"
      />
    </div>
  );
};

export default VideoCard;

```

Here's the problem: I don't know how to build this app into a dockerfile, and I am using this on docker. @will-moss would you please make the necessary changes so I can use this repo? Thanks.

**Comment by will-moss** [comment]
Hi,

Thanks a lot for opening the issue, as well as for the code excerpt.

I have just published a new version that should fix the issue.

You can pull the latest image.

Does it work well on your end?

(I had to tweak the code as it would break on my end due to `new URL()` and `pathname` not parsing properly the URL when it had `#` and `@` symbols. So I went for a simpler alternative : Given that we know the filename (`xxx.mp4`), let's just replace that part only, without parsing or any other treatment — just a `url.replace(filename, encoded filename)`.

Thanks again

**Comment by DavidSpivey** [comment]
Thanks for the quick response!
I tried the latest update (v1.18.4), and while one or two shorter file names with # did play successfully (thanks for that), others did not. 
I think perhaps the preload is failing to url encode.
Here are some example failures.

```
Worked:
http://192.168.1.5:8015/media/Name%20conflict/Myron%20Golden%20Clips%20-%20Why%20you%20need%20to%20stop%20saying%20%E2%80%9CIt%20cost%20too%20much%E2%80%9D%20%23myrongolden%20%23myrongoldenquotes%20%23myrongoldenclips%20%23business%20%23enterpreneur%20%23mindset%20%23successful%20%23success%20.mp4?hash=

Failed (too many to count):
http://192.168.1.5:8015/media/IUBIRE%20-%20TikTok%20video%20#7492503752713276694.mp4?hash=
http://192.168.1.5:8015/media/mick1916%20-%20#fyp%20#stuck%20#foryoupage%20.mp4?hash=
```

**Comment by will-moss** [comment]
You're welcome, and thanks a lot for your quick report.

Just in case, and by any chance, does private browsing / clearing the cache fix the issue?

Just before releasing, I was having the issue, and I found in my Network Inspector in Chrome Devtools that the MP4 files were served from the Disk Cache. But, curiously, it was an error / black media that was served from the Disk Cache, rather than the actual file. As soon as I toggled the checkbox "Disable cache" and refreshed, it all worked again.

Another idea, you could run `localStorage.removeItem('erin_videos')` to disable the preload. (I'm thinking of removing that feature completely as I found it's not working as intended and leads to unexpected flashes of content while everything loads, while not giving any real UX improvement)

**Comment by DavidSpivey** [comment]
I tried Chrome, Firefox, and Edge. Some of them don't even show the error in the console. The only one that lets me know the preload failed is Firefox.

On Chrome, checking disable cache as you did, in incognito, still the error persists.

Example failures in Chrome with cache disabled.
```
http://192.168.1.5:8015/media/Wally%20-%20TikTok%20video%20#7512536625923050798.mp4?hash=
http://192.168.1.5:8015/media/ESPNatbat%20-%20At%20first%20I%20thought%20the%20video%20just%20rewinded%20%F0%9F%98%B1%20(via%20@Darius%20Gaddy,%20@(Dee-loe)%20#SlimReaper)%20#baseball%20#wow%20#real%20#incredible%20.mp4?hash=
```

**Comment by will-moss** [comment]
The issue was the following : The lazyloading mechanism was updating the page's DOM directly, bypassing the `VideoCard` component, and using the old encoding system that didn't support the # and @ characters. It's my mistake for missing it in the previous release. Very sorry for that.

I've just published a new version with the code updated, and it should now be sorted.

You can pull the latest image.

(Also : Your observation was on point : The videos would load perfectly if they were within the first loaded ones, but they would break if they were lazyloaded, explaining what you've encountered).
